POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVjOWJjM2QyMjgzMTNjNjhjYjkzN2QwMCIsImlhdCI6MTU1MzcxMjgwNH0.Tic10YUIFuNMxXDq_arf-IbbYFRmjem44V89wRRQgcQ

{
    "title": "Otsikko 3",
    "author": "BBBB",
    "url": "http://testi123.testi3",
    "likes": 0
}